version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - backend
    dns:
      - 8.8.8.8

  db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env.db  # Referência ao arquivo de ambiente
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"  # Garante a codificação UTF-8
    networks:
      - backend
    dns:
      - 8.8.8.8

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
