version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - backend
    dns:
      - 8.8.8.8  # Adicionando servidor DNS

  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_USER=bookstore
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=banco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend
    dns:
      - 8.8.8.8  # Adicionando servidor DNS

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
