version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - app_data:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bookstore_dev
      - POSTGRES_PASSWORD=bookstore_dev
      - POSTGRES_DB=bookstore_dev
    ports: 
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  app_data:







# version: '3.9'

# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - app_data:/usr/src/app/   # Corrigido o espaço extra
#     ports:
#       - 8000:8000
#     env_file:
#       - ./.env.dev
#     networks:
#       - backend
#     depends_on:
#       - db

#   db:
#     image: postgres:13.0-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_USER=bookstore_dev
#       - POSTGRES_PASSWORD=bookstore_dev
#       - POSTGRES_DB=bookstore_dev  # Alterado para alinhar com o .env
#     ports:  # Adicionei esta seção para mapear a porta 5432
#       - "5432:5432"
#     networks:
#       - backend

# networks:
#   backend:
#     driver: bridge

# volumes:
#   postgres_data:
#   app_data:
