name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12.2]

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.0-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: bookstore_dev
          POSTGRES_PASSWORD: bookstore_dev
          POSTGRES_DB: bookstore_dev_db
        options: >-
          --health-cmd="pg_isready -U bookstore_dev -d bookstore_dev_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry

    - name: Install dependencies
      run: poetry install

    - name: Wait for Postgres to be ready
      run: |
        until pg_isready -h db -p 5432; do echo "Waiting for Postgres..."; sleep 5; done

    - name: Run tests
      env:
        DATABASE_URL: postgres://bookstore_dev:bookstore_dev@db:5432/bookstore_dev_db
      run: |
        poetry run python manage.py test
